import { ImageResponse } from "@vercel/og";

export const runtime = "edge";

export async function GET(request: Request) {
  const { searchParams } = new URL(request.url);
  const isp = searchParams.get("isp") ?? "ISP";
  const plan = searchParams.get("plan") ?? "Plan";
  const promised = Number(searchParams.get("promised") ?? 100);
  const actual = Number(searchParams.get("actual") ?? 85);
  const score = Number(searchParams.get("score") ?? 72);
  const grade = searchParams.get("grade") ?? "B";
  const owed = Number(searchParams.get("owed") ?? 320);
  const ratio =
    promised > 0 ? Math.min(100, Math.round((actual / promised) * 100)) : 0;
  const total = owed + 750;

  return new ImageResponse(
    (
      <div
        style={{
          background: "#0a0a0f",
          color: "white",
          width: "1200px",
          height: "630px",
          display: "flex",
          flexDirection: "column",
          padding: "48px",
          border: "2px solid rgba(255,255,255,0.1)",
          fontFamily: "monospace",
        }}
      >
        <div style={{ display: "flex", justifyContent: "space-between" }}>
          <div style={{ fontSize: 32, fontWeight: 700 }}>
            ⚡ PULSE SERVICE AUDIT INVOICE
          </div>
          <div style={{ fontSize: 18, color: "#a0a0b0" }}>
            Invoice #: PLS-2026-{Math.floor(Math.random() * 90000 + 10000)}
          </div>
        </div>

        <div
          style={{
            marginTop: 24,
            padding: "18px 20px",
            border: "1px solid rgba(255,255,255,0.12)",
            background: "#12121a",
            fontSize: 18,
          }}
        >
          BILL TO: {isp} Customer Care
        </div>

        <div
          style={{
            marginTop: 24,
            display: "flex",
            gap: "40px",
            fontSize: 20,
          }}
        >
          <div>
            <div>Plan: {plan}</div>
            <div>Promised: {promised} Mbps</div>
            <div>Delivered: {actual} Mbps ({ratio}%)</div>
          </div>
          <div>
            <div>Service Score: {score}/100</div>
            <div>Grade: {grade}</div>
          </div>
        </div>

        <div
          style={{
            marginTop: 28,
            borderTop: "1px solid rgba(255,255,255,0.1)",
            paddingTop: 20,
            fontSize: 20,
          }}
        >
          <div style={{ fontSize: 22, marginBottom: 12 }}>AMOUNT DUE</div>
          <div style={{ display: "flex", justifyContent: "space-between" }}>
            <span>Undelivered Service</span>
            <span>₹{owed}</span>
          </div>
          <div style={{ display: "flex", justifyContent: "space-between" }}>
            <span>Emotional Damages</span>
            <span>₹500.00</span>
          </div>
          <div style={{ display: "flex", justifyContent: "space-between" }}>
            <span>Customer Care Hold Time</span>
            <span>₹250.00</span>
          </div>
          <div
            style={{
              marginTop: 12,
              borderTop: "1px solid rgba(255,255,255,0.2)",
              paddingTop: 12,
              display: "flex",
              justifyContent: "space-between",
              fontSize: 24,
              fontWeight: 700,
              color: "#00f0ff",
            }}
          >
            <span>TOTAL OWED</span>
            <span>₹{total}</span>
          </div>
        </div>

        <div
          style={{
            marginTop: "auto",
            display: "flex",
            justifyContent: "space-between",
            fontSize: 14,
            color: "#a0a0b0",
          }}
        >
          <span>Generated by pulse.vercel.app</span>
          <span>“They promised. We measured.”</span>
        </div>
      </div>
    ),
    {
      width: 1200,
      height: 630,
    }
  );
}
